# Generated by Django 4.1.3 on 2022-11-24 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdtCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.FloatField()),
                ('level', models.PositiveIntegerField()),
                ('character_class', models.CharField(max_length=100)),
                ('alignment', models.CharField(max_length=100)),
                ('gold', models.IntegerField()),
            ],
        ),
    ]
