# Generated by Django 4.1.3 on 2022-12-04 14:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AdtCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(default='/', max_length=200)),
                ('name', models.CharField(db_index=True, default='no name', max_length=150)),
                ('age', models.FloatField(default=0)),
                ('gender', models.CharField(default='U', max_length=1)),
                ('charisma', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('character_class', models.CharField(blank=True, db_index=True, max_length=100)),
                ('race', models.CharField(default='human', max_length=50)),
                ('alignment', models.CharField(default='neutral', max_length=100)),
                ('platinum', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('copper', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('created_by', models.CharField(default='unknown', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='character_class', to='characters.category')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
