# Generated by Django 4.1.3 on 2022-11-24 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtcharacter',
            name='created_by',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
