# Generated by Django 4.1.3 on 2022-12-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtcharacter',
            name='gender',
            field=models.CharField(default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='adtcharacter',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
