# Generated by Django 4.1.3 on 2022-11-24 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_adtcharacter_created_by_adtcharacter_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtcharacter',
            name='charisma',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='constitution',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='copper',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='dexterity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='intelligence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='platinum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='race',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='silver',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='strength',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtcharacter',
            name='wisdom',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
